baseURL = "https://emersonrealestateblogs.netlify.app/"
languageCode = "en-us"
title = "Emerson Real Estate Blogs"
theme = "ananke"

# Enable sitemap
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# Enable outputs (for RSS and JSON feeds too)
[outputs]
  home = ["HTML", "RSS"]

# Params (for SEO and custom CSS)
[params]
  description = "Your trusted source for real estate investing tips, wholesaling strategies, and market insights."
  author = "Emerson Real Estate"
  custom_css = ["css/custom.css"]   # ensure your CSS is applied

# Allow raw HTML in Markdown
[markup.goldmark.renderer]
  unsafe = true
